services:
  db:
    image: postgres:15-alpine
    container_name: project_03-db
    environment:
      POSTGRES_DB: "notes_db_03"
      POSTGRES_USER: "notes_user_03"
      POSTGRES_PASSWORD: "password123"
    volumes:
      - pgdata_03:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5403:5432"
    networks:
      - project_03-network

  backend:
    build:
      context: ./backend
    container_name: project_03-backend
    environment:
      DB_HOST: db
      DB_NAME: "notes_db_03"
      DB_USER: "notes_user_03"
      DB_PASS: "password123"
    ports:
      - "5003:5000"
    depends_on:
      - db
    networks:
      - project_03-network

  nginx:
    image: nginx:alpine
    container_name: project_03-nginx
    ports:
      - "8003:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - project_03-network

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: project_03-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9003:9090"
    depends_on:
      - backend
    networks:
      - project_03-network

  grafana:
    image: grafana/grafana:10.0.0
    container_name: project_03-grafana
    ports:
      - "3003:3000"
    depends_on:
      - prometheus
    networks:
      - project_03-network

volumes:
  pgdata_03:

networks:
  project_03-network:
    name: project_03-network
